version: '3.4'
services:
  rotki.avado.dnp.dappnode.eth:
    image: 'rotki.avado.dnp.dappnode.eth:0.0.15'
    build:
      context: ./build
      args:
        VERSION: v1.25.3
    volumes:
      - 'data:/data'
      - 'logs:/logs'
    ports:
      - '4443:433'
    environment:
      - EXTRA_OPTS=
volumes:
  data: {}
  logs: {}
